#!/usr/bin/env python3
"""
find-section.py — index of section markers in index.html.

The file is one long single-page app. To navigate without endless scrolling,
the original author marked sections with /* ---------- Name ---------- */
comments inside the inline <style> and the inline <script>. This script:

  - lists every section with its line number,
  - filters by name,
  - rewrites a TOC comment block at the top of the inline <script> so the
    table of contents is visible the moment you open the file.

USAGE:
    python find-section.py                # list every section
    python find-section.py --name api     # case-insensitive substring filter
    python find-section.py --toc          # print TOC block to stdout
    python find-section.py --update-toc   # rewrite TOC block inside index.html

The script never touches your code; it only reads section markers and
rewrites the block delimited by:

    /* === BEGIN TOC ... === */
    ...
    /* === END TOC === */

If the block is absent, --update-toc inserts it directly after the
"ReadPaper2U — single-file app" header comment.
"""

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
HTML_PATH = HERE / 'index.html'

SECTION_RE = re.compile(r'/\*\s*-+\s*(.+?)\s*-+\s*\*/')
STYLE_END_RE = re.compile(r'</style>', re.IGNORECASE)

TOC_BEGIN = '/* === BEGIN TOC (regenerated by find-section.py --update-toc) === */'
TOC_END = '/* === END TOC === */'

ANCHOR = (
    '/* =====================================================================\n'
    ' * ReadPaper2U — single-file app\n'
    ' * ===================================================================== */'
)


def find_sections(text):
    """Return [(line_no, scope, name)] for every /* ----- Name ----- */ marker."""
    lines = text.split('\n')
    style_end = next(
        (i for i, ln in enumerate(lines, 1) if STYLE_END_RE.search(ln)),
        None,
    )
    sections = []
    for i, ln in enumerate(lines, 1):
        if TOC_BEGIN in ln or TOC_END in ln:
            continue
        m = SECTION_RE.search(ln)
        if not m:
            continue
        name = m.group(1).strip()
        scope = 'JS' if (style_end and i > style_end) else 'CSS'
        sections.append((i, scope, name))
    return sections


def format_listing(sections):
    if not sections:
        return '(no sections matched)'
    out = []
    last_scope = None
    for line_no, scope, name in sections:
        if scope != last_scope:
            if last_scope is not None:
                out.append('')
            out.append(f'{scope}:')
            last_scope = scope
        out.append(f'  L{line_no:>5}  {name}')
    return '\n'.join(out)


def render_toc_block(sections):
    body = ['/*']
    body.append(' * Section index (auto-regenerated; run: python find-section.py --update-toc)')
    body.append(' *')
    for ln in format_listing(sections).split('\n'):
        body.append(' *' + (' ' + ln if ln else ''))
    body.append(' */')
    return TOC_BEGIN + '\n' + '\n'.join(body) + '\n' + TOC_END


def replace_toc(text, new_block):
    pattern = re.compile(
        re.escape(TOC_BEGIN) + r'.*?' + re.escape(TOC_END),
        re.DOTALL,
    )
    return pattern.sub(new_block, text, count=1)


def update_toc(text, sections):
    new_block = render_toc_block(sections)

    if TOC_BEGIN in text and TOC_END in text:
        text = replace_toc(text, new_block)
        action = 'replaced'
    else:
        if ANCHOR not in text:
            sys.stderr.write(
                'ERROR: header anchor not found in index.html; cannot insert TOC.\n'
                'Expected the comment block:\n' + ANCHOR + '\n'
            )
            sys.exit(1)
        text = text.replace(ANCHOR, ANCHOR + '\n\n' + new_block, 1)
        action = 'inserted'

    # Inserting / replacing the block shifts every line below it. Re-scan and
    # rewrite the TOC once more so the embedded line numbers reflect the file
    # as it now stands. The block size is identical on this second pass, so a
    # third pass would be a no-op.
    sections = find_sections(text)
    new_block = render_toc_block(sections)
    text = replace_toc(text, new_block)

    HTML_PATH.write_bytes(text.encode('utf-8'))
    print(f'TOC {action} — {len(sections)} sections, {len(text.split(chr(10)))} total lines.')


def main():
    parser = argparse.ArgumentParser(
        description='List section markers in index.html, optionally inject a TOC.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('--name', help='filter by name (case-insensitive substring)')
    parser.add_argument('--toc', action='store_true', help='print TOC block to stdout')
    parser.add_argument('--update-toc', action='store_true', help='write TOC block into index.html')
    args = parser.parse_args()

    if not HTML_PATH.exists():
        sys.stderr.write(f'ERROR: not found: {HTML_PATH}\n')
        sys.exit(1)

    text = HTML_PATH.read_bytes().decode('utf-8')
    sections = find_sections(text)

    if args.update_toc:
        update_toc(text, sections)
        return
    if args.toc:
        print(render_toc_block(sections))
        return
    if args.name:
        needle = args.name.lower()
        sections = [s for s in sections if needle in s[2].lower()]
    print(format_listing(sections))


if __name__ == '__main__':
    main()
